[package]
name = "no0101_0150"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "no0104"
path = "src/no0104.rs"

[[bin]]
name = "no0111"
path = "src/no0111.rs"